/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bricked_wall.glb -o src/components/Wall.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';

export function Wall(props) {
  const { nodes, materials } = useGLTF('/models/bricked_wall.glb');
  const group = useRef();

  useEffect(() => {
    if (!group.current) return;

    const groupWorldPosition = new THREE.Vector3();
    group.current.getWorldPosition(groupWorldPosition);

    group.current.children.forEach((mesh) => {
      mesh.originalPosition = mesh.position.clone();
      
      const meshWorldPosition = new THREE.Vector3();
      mesh.getWorldPosition(meshWorldPosition);

      mesh.directionVector = meshWorldPosition
        .clone()
        .sub(groupWorldPosition)
        .normalize();
      
      // Posição alvo (explodida)
      mesh.targetPosition = mesh.originalPosition
        .clone()
        .add(mesh.directionVector.clone().multiplyScalar(3));
    });
  }, []);

  const scrollData = useScroll();

  useFrame(() => {
    if (!group.current) return;

    group.current.children.forEach((mesh) => {
      if (scrollData.offset < 0.5) {
        if (mesh.name === "Path_Straight") {
          mesh.visible = true;
        } else {
          mesh.visible = false;
        }
      } else {
        if (mesh.name === "Path_Straight") {
          mesh.visible = false;
        } else {
          mesh.visible = true;
        }
      }

      // Animação de explosão - CORRIGIDO
      if (scrollData.offset > 0.625) {
        // Calcular o progresso da animação (0 a 1)
        // Começar a animação em 0.625 e terminar em 1.0
        const animationProgress = Math.min((scrollData.offset - 0.625) / (1.0 - 0.625), 1);
        
        mesh.position.x = THREE.MathUtils.lerp(
          mesh.originalPosition.x,
          mesh.targetPosition.x,
          animationProgress
        );
        mesh.position.y = THREE.MathUtils.lerp(
          mesh.originalPosition.y,
          mesh.targetPosition.y,
          animationProgress
        );
        mesh.position.z = THREE.MathUtils.lerp(
          mesh.originalPosition.z,
          mesh.targetPosition.z,
          animationProgress
        );
      } else {
        // Garantir que as peças estejam na posição original quando scroll < 0.625
        mesh.position.copy(mesh.originalPosition);
      }
    });
  });



  return (
    <group {...props} dispose={null} ref={group}>
      <group position={[0.097, 0.009, -0.432]}>
        <mesh geometry={nodes.Path_Straight_cell093_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell093_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[-0.108, 0.032, 0.47]}>
        <mesh geometry={nodes.Path_Straight_cell001_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell001_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.054, 0.032, -0.345]}>
        <mesh geometry={nodes.Path_Straight_cell002_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell002_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell004.geometry} material={materials.Stone_Dark} position={[-0.044, 0.01, -0.271]} />
      <mesh geometry={nodes.Path_Straight_cell005.geometry} material={materials.Stone_Dark} position={[0.025, 0.01, 0.474]} />
      <mesh geometry={nodes.Path_Straight_cell006.geometry} material={materials.Stone_Dark} position={[0.039, 0.031, 0.001]} />
      <group position={[0.101, 0.033, -0.135]}>
        <mesh geometry={nodes.Path_Straight_cell006_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell006_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell008.geometry} material={materials.Stone_Light} position={[0.085, 0.032, 0.202]} />
      <group position={[0.116, 0.011, -0.479]}>
        <mesh geometry={nodes.Path_Straight_cell008_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell008_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell010.geometry} material={materials.Stone_Light} position={[-0.152, 0.025, -0.387]} />
      <mesh geometry={nodes.Path_Straight_cell011.geometry} material={materials.Stone_Dark} position={[0.215, 0.031, 0.054]} />
      <group position={[0.064, 0.031, 0.471]}>
        <mesh geometry={nodes.Path_Straight_cell011_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell011_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.088, 0.029, 0.439]}>
        <mesh geometry={nodes.Path_Straight_cell012_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell012_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell014.geometry} material={materials.Stone_Dark} position={[-0.058, 0.027, 0.437]} />
      <mesh geometry={nodes.Path_Straight_cell016.geometry} material={materials.Stone_Dark} position={[-0.021, 0.032, -0.137]} />
      <mesh geometry={nodes.Path_Straight_cell017.geometry} material={materials.Stone_Dark} position={[-0.224, 0.025, 0.459]} />
      <group position={[-0.02, 0.036, 0.472]}>
        <mesh geometry={nodes.Path_Straight_cell017_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell017_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell019.geometry} material={materials.Stone_Dark} position={[0.021, 0.029, -0.173]} />
      <mesh geometry={nodes.Path_Straight_cell020.geometry} material={materials.Stone_Dark} position={[-0.151, 0.027, -0.095]} />
      <group position={[0.028, 0.027, 0.251]}>
        <mesh geometry={nodes.Path_Straight_cell020_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell020_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.078, 0.031, -0.471]}>
        <mesh geometry={nodes.Path_Straight_cell021_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell021_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell023.geometry} material={materials.Stone_Dark} position={[-0.216, 0.028, -0.348]} />
      <mesh geometry={nodes.Path_Straight_cell024.geometry} material={materials.Stone_Dark} position={[0.24, 0.023, 0.32]} />
      <group position={[0.047, 0.035, -0.269]}>
        <mesh geometry={nodes.Path_Straight_cell024_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell024_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell033.geometry} material={materials.Stone_Light} position={[0.099, 0.013, 0.209]} />
      <mesh geometry={nodes.Path_Straight_cell034.geometry} material={materials.Stone_Dark} position={[0.055, 0.029, -0.15]} />
      <mesh geometry={nodes.Path_Straight_cell035.geometry} material={materials.Stone_Dark} position={[-0.152, 0.027, -0.125]} />
      <group position={[0.037, 0.028, 0.077]}>
        <mesh geometry={nodes.Path_Straight_cell035_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell035_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell037.geometry} material={materials.Stone_Dark} position={[0.038, 0.03, -0.077]} />
      <mesh geometry={nodes.Path_Straight_cell038.geometry} material={materials.Stone_Dark} position={[-0.072, 0.023, -0.477]} />
      <mesh geometry={nodes.Path_Straight_cell039.geometry} material={materials.Stone_Light} position={[-0.138, 0.029, -0.295]} />
      <mesh geometry={nodes.Path_Straight_cell040.geometry} material={materials.Stone_Dark} position={[-0.218, 0.025, -0.441]} />
      <group position={[-0.123, 0.034, 0.369]}>
        <mesh geometry={nodes.Path_Straight_cell040_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell040_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.08, 0.031, -0.441]}>
        <mesh geometry={nodes.Path_Straight_cell042.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell042_1.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell045.geometry} material={materials.Stone_Dark} position={[-0.045, 0.03, -0.338]} />
      <mesh geometry={nodes.Path_Straight_cell046.geometry} material={materials.Stone_Dark} position={[0.199, 0.031, -0.324]} />
      <mesh geometry={nodes.Path_Straight_cell047.geometry} material={materials.Stone_Light} position={[-0.18, 0.025, 0.054]} />
      <mesh geometry={nodes.Path_Straight_cell048.geometry} material={materials.Stone_Dark} position={[-0.214, 0.025, -0.118]} />
      <mesh geometry={nodes.Path_Straight_cell049.geometry} material={materials.Stone_Dark} position={[-0.046, 0.03, -0.008]} />
      <group position={[-0.043, 0.031, 0.135]}>
        <mesh geometry={nodes.Path_Straight_cell049_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell049_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[-0.093, 0.031, -0.015]}>
        <mesh geometry={nodes.Path_Straight_cell051.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell051_1.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell053.geometry} material={materials.Stone_Dark} position={[-0.05, 0.029, 0.025]} />
      <group position={[-0.179, 0.031, 0.388]}>
        <mesh geometry={nodes.Path_Straight_cell053_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell053_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell055.geometry} material={materials.Stone_Light} position={[-0.228, 0.029, 0.357]} />
      <mesh geometry={nodes.Path_Straight_cell056.geometry} material={materials.Stone_Light} position={[-0.235, 0.025, 0.289]} />
      <mesh geometry={nodes.Path_Straight_cell057.geometry} material={materials.Stone_Dark} position={[0.225, 0.03, -0.256]} />
      <mesh geometry={nodes.Path_Straight_cell058.geometry} material={materials.Stone_Light} position={[-0.202, 0.027, 0.298]} />
      <mesh geometry={nodes.Path_Straight_cell059.geometry} material={materials.Stone_Light} position={[0.127, 0.028, 0.322]} />
      <mesh geometry={nodes.Path_Straight_cell061.geometry} material={materials.Stone_Dark} position={[-0.126, 0.026, -0.188]} />
      <mesh geometry={nodes.Path_Straight_cell062.geometry} material={materials.Stone_Dark} position={[-0.163, 0.011, 0.479]} />
      <mesh geometry={nodes.Path_Straight_cell064.geometry} material={materials.Stone_Light} position={[0.169, 0.012, 0.313]} />
      <mesh geometry={nodes.Path_Straight_cell065.geometry} material={materials.Stone_Light} position={[0.162, 0.025, -0.458]} />
      <mesh geometry={nodes.Path_Straight_cell067.geometry} material={materials.Stone_Dark} position={[-0.057, 0.025, 0.406]} />
      <mesh geometry={nodes.Path_Straight_cell068.geometry} material={materials.Stone_Dark} position={[0.037, 0.01, -0.269]} />
      <mesh geometry={nodes.Path_Straight_cell069.geometry} material={materials.Stone_Dark} position={[0.023, 0.033, 0.417]} />
      <mesh geometry={nodes.Path_Straight_cell070.geometry} material={materials.Stone_Dark} position={[0.228, 0.028, -0.215]} />
      <mesh geometry={nodes.Path_Straight_cell072.geometry} material={materials.Stone_Dark} position={[-0.019, 0.028, 0.372]} />
      <mesh geometry={nodes.Path_Straight_cell073.geometry} material={materials.Stone_Dark} position={[0.135, 0.025, -0.011]} />
      <mesh geometry={nodes.Path_Straight_cell074.geometry} material={materials.Stone_Light} position={[0.148, 0.01, 0.397]} />
      <mesh geometry={nodes.Path_Straight_cell075.geometry} material={materials.Stone_Dark} position={[-0.035, 0.032, -0.079]} />
      <mesh geometry={nodes.Path_Straight_cell076.geometry} material={materials.Stone_Dark} position={[-0.135, 0.024, 0.413]} />
      <mesh geometry={nodes.Path_Straight_cell077.geometry} material={materials.Stone_Light} position={[0.055, 0.028, 0.186]} />
      <mesh geometry={nodes.Path_Straight_cell078.geometry} material={materials.Stone_Dark} position={[0.125, 0.025, -0.258]} />
      <mesh geometry={nodes.Path_Straight_cell079.geometry} material={materials.Stone_Dark} position={[-0.227, 0.026, -0.2]} />
      <group position={[-0.115, 0.035, -0.024]}>
        <mesh geometry={nodes.Path_Straight_cell080.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell080_1.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.165, 0.033, 0.256]}>
        <mesh geometry={nodes.Path_Straight_cell082.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell082_1.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell085.geometry} material={materials.Stone_Light} position={[0.164, 0.025, -0.1]} />
      <group position={[-0.027, 0.033, -0.263]}>
        <mesh geometry={nodes.Path_Straight_cell085_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell085_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.047, 0.011, 0.142]}>
        <mesh geometry={nodes.Path_Straight_cell086_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell086_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell089.geometry} material={materials.Stone_Dark} position={[-0.049, 0.026, -0.163]} />
      <group position={[0.118, 0.032, 0.438]}>
        <mesh geometry={nodes.Path_Straight_cell089_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell089_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell091.geometry} material={materials.Stone_Dark} position={[0.236, 0.029, -0.337]} />
      <mesh geometry={nodes.Path_Straight_cell092.geometry} material={materials.Stone_Dark} position={[0.123, 0.012, -0.387]} />
      <mesh geometry={nodes.Path_Straight_cell093.geometry} material={materials.Stone_Dark} position={[0.077, 0.013, -0.398]} />
      <group position={[-0.158, 0.035, 0.464]}>
        <mesh geometry={nodes.Path_Straight_cell096_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell096_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.005, 0.04, -0.431]}>
        <mesh geometry={nodes.Path_Straight_cell097_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell097_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell097.geometry} material={materials.Stone_Light} position={[0.02, 0.036, -0.392]} />
      <mesh geometry={nodes.Path_Straight_cell098.geometry} material={materials.Stone_Dark} position={[0.064, 0.012, 0.478]} />
      <group position={[0.091, 0.033, -0.191]}>
        <mesh geometry={nodes.Path_Straight_cell100_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell100_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell100.geometry} material={materials.Stone_Light} position={[0.153, 0.033, -0.135]} />
      <group position={[0.148, 0.033, -0.187]}>
        <mesh geometry={nodes.Path_Straight_cell102_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell102_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.126, 0.03, 0.134]}>
        <mesh geometry={nodes.Path_Straight_cell103_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell103_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.131, 0.035, 0.225]}>
        <mesh geometry={nodes.Path_Straight_cell104_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell104_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.096, 0.03, 0.141]}>
        <mesh geometry={nodes.Path_Straight_cell105_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell105_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell105.geometry} material={materials.Stone_Light} position={[-0.035, 0.038, -0.416]} />
      <mesh geometry={nodes.Path_Straight_cell106.geometry} material={materials.Stone_Dark} position={[-0.081, 0.028, -0.389]} />
      <mesh geometry={nodes.Path_Straight_cell107.geometry} material={materials.Stone_Dark} position={[-0.07, 0.031, -0.439]} />
      <group position={[-0.188, 0.035, -0.396]}>
        <mesh geometry={nodes.Path_Straight_cell109_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell109_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell109.geometry} material={materials.Stone_Dark} position={[0.167, 0.029, 0.053]} />
      <mesh geometry={nodes.Path_Straight_cell110.geometry} material={materials.Stone_Dark} position={[0.19, 0.035, -0.031]} />
      <group position={[0.014, 0.032, 0.467]}>
        <mesh geometry={nodes.Path_Straight_cell112_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell112_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell112.geometry} material={materials.Stone_Light} position={[0.114, 0.032, 0.382]} />
      <group position={[0.087, 0.026, 0.394]}>
        <mesh geometry={nodes.Path_Straight_cell114_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell114_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell114.geometry} material={materials.Stone_Dark} position={[-0.021, 0.033, 0.44]} />
      <mesh geometry={nodes.Path_Straight_cell115.geometry} material={materials.Stone_Dark} position={[-0.012, 0.032, -0.185]} />
      <group position={[-0.069, 0.034, 0.472]}>
        <mesh geometry={nodes.Path_Straight_cell117_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell117_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell117.geometry} material={materials.Stone_Dark} position={[-0.149, 0.024, -0.061]} />
      <mesh geometry={nodes.Path_Straight_cell118.geometry} material={materials.Stone_Dark} position={[-0.114, 0.03, -0.065]} />
      <mesh geometry={nodes.Path_Straight_cell119.geometry} material={materials.Stone_Light} position={[0.102, 0.004, 0.264]} />
      <mesh geometry={nodes.Path_Straight_cell121.geometry} material={materials.Stone_Light} position={[-0.175, 0.027, -0.339]} />
      <mesh geometry={nodes.Path_Straight_cell122.geometry} material={materials.Stone_Dark} position={[0.234, 0.025, 0.255]} />
      <mesh geometry={nodes.Path_Straight_cell123.geometry} material={materials.Stone_Dark} position={[0.123, 0.011, 0.195]} />
      <mesh geometry={nodes.Path_Straight_cell124.geometry} material={materials.Stone_Dark} position={[0.098, 0.007, 0.145]} />
      <mesh geometry={nodes.Path_Straight_cell125.geometry} material={materials.Stone_Dark} position={[-0.113, 0.024, -0.127]} />
      <mesh geometry={nodes.Path_Straight_cell126.geometry} material={materials.Stone_Dark} position={[-0.183, 0.03, -0.165]} />
      <mesh geometry={nodes.Path_Straight_cell127.geometry} material={materials.Stone_Dark} position={[0.111, 0.025, 0.095]} />
      <group position={[-0.122, 0.035, -0.225]}>
        <mesh geometry={nodes.Path_Straight_cell129_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell129_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell129.geometry} material={materials.Stone_Dark} position={[-0.093, 0.025, -0.246]} />
      <mesh geometry={nodes.Path_Straight_cell130.geometry} material={materials.Stone_Dark} position={[-0.091, 0.026, -0.308]} />
      <mesh geometry={nodes.Path_Straight_cell131.geometry} material={materials.Stone_Dark} position={[-0.161, 0.022, -0.453]} />
      <mesh geometry={nodes.Path_Straight_cell132.geometry} material={materials.Stone_Light} position={[-0.177, 0.025, -0.415]} />
      <group position={[-0.134, 0.041, 0.432]}>
        <mesh geometry={nodes.Path_Straight_cell134_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell134_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell134.geometry} material={materials.Stone_Dark} position={[-0.092, 0.029, 0.41]} />
      <group position={[0.124, 0.034, -0.389]}>
        <mesh geometry={nodes.Path_Straight_cell136_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell136_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.073, 0.035, -0.405]}>
        <mesh geometry={nodes.Path_Straight_cell137_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell137_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell137.geometry} material={materials.Stone_Light} position={[0.039, 0.036, -0.417]} />
      <mesh geometry={nodes.Path_Straight_cell138.geometry} material={materials.Stone_Dark} position={[-0.103, 0.01, -0.353]} />
      <mesh geometry={nodes.Path_Straight_cell139.geometry} material={materials.Stone_Light} position={[-0.114, 0.006, -0.351]} />
      <mesh geometry={nodes.Path_Straight_cell140.geometry} material={materials.Stone_Dark} position={[0.142, 0.037, -0.337]} />
      <mesh geometry={nodes.Path_Straight_cell141.geometry} material={materials.Stone_Dark} position={[-0.21, 0.025, 0.061]} />
      <mesh geometry={nodes.Path_Straight_cell142.geometry} material={materials.Stone_Dark} position={[-0.248, 0.001, 0.072]} />
      <mesh geometry={nodes.Path_Straight_cell143.geometry} material={materials.Stone_Dark} position={[-0.188, 0.031, -0.013]} />
      <group position={[-0.225, 0.036, -0.16]}>
        <mesh geometry={nodes.Path_Straight_cell145_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell145_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell145.geometry} material={materials.Stone_Dark} position={[-0.216, 0.029, -0.059]} />
      <mesh geometry={nodes.Path_Straight_cell146.geometry} material={materials.Stone_Light} position={[-0.118, 0.03, 0.057]} />
      <group position={[-0.089, 0.028, 0.043]}>
        <mesh geometry={nodes.Path_Straight_cell148_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell148_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell148.geometry} material={materials.Stone_Dark} position={[-0.214, 0.005, 0.489]} />
      <group position={[-0.202, 0.026, 0.195]}>
        <mesh geometry={nodes.Path_Straight_cell150_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell150_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell150.geometry} material={materials.Stone_Dark} position={[-0.226, 0.022, 0.133]} />
      <mesh geometry={nodes.Path_Straight_cell151.geometry} material={materials.Stone_Dark} position={[-0.154, 0.025, 0.257]} />
      <mesh geometry={nodes.Path_Straight_cell152.geometry} material={materials.Stone_Dark} position={[-0.142, 0.026, 0.318]} />
      <mesh geometry={nodes.Path_Straight_cell153.geometry} material={materials.Stone_Dark} position={[-0.078, 0.029, 0.273]} />
      <group position={[-0.094, 0.035, 0.329]}>
        <mesh geometry={nodes.Path_Straight_cell155_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell155_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[-0.037, 0.04, 0.244]}>
        <mesh geometry={nodes.Path_Straight_cell156_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell156_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.087, 0.025, 0.311]}>
        <mesh geometry={nodes.Path_Straight_cell157_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell157_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell157.geometry} material={materials.Stone_Dark} position={[0.119, 0.026, 0.266]} />
      <mesh geometry={nodes.Path_Straight_cell158.geometry} material={materials.Stone_Dark} position={[-0.096, 0.022, -0.187]} />
      <mesh geometry={nodes.Path_Straight_cell159.geometry} material={materials.Stone_Dark} position={[-0.09, 0.029, -0.14]} />
      <mesh geometry={nodes.Path_Straight_cell160.geometry} material={materials.Stone_Dark} position={[-0.108, 0.01, 0.479]} />
      <mesh geometry={nodes.Path_Straight_cell161.geometry} material={materials.Stone_Dark} position={[0.201, 0.012, 0.324]} />
      <mesh geometry={nodes.Path_Straight_cell162.geometry} material={materials.Stone_Dark} position={[0.17, 0.012, 0.271]} />
      <mesh geometry={nodes.Path_Straight_cell163.geometry} material={materials.Stone_Dark} position={[0.248, 0.001, 0.366]} />
      <mesh geometry={nodes.Path_Straight_cell164.geometry} material={materials.Stone_Dark} position={[0.161, 0.028, -0.398]} />
      <mesh geometry={nodes.Path_Straight_cell165.geometry} material={materials.Stone_Dark} position={[0.217, 0.024, -0.436]} />
      <mesh geometry={nodes.Path_Straight_cell166.geometry} material={materials.Stone_Dark} position={[-0.026, 0.029, 0.409]} />
      <mesh geometry={nodes.Path_Straight_cell167.geometry} material={materials.Stone_Dark} position={[0.06, 0.027, 0.42]} />
      <mesh geometry={nodes.Path_Straight_cell169.geometry} material={materials.Stone_Dark} position={[-0.074, 0.033, 0.361]} />
      <mesh geometry={nodes.Path_Straight_cell170.geometry} material={materials.Stone_Dark} position={[0.125, 0.029, 0.056]} />
      <mesh geometry={nodes.Path_Straight_cell171.geometry} material={materials.Stone_Dark} position={[0.088, 0.025, 0.032]} />
      <mesh geometry={nodes.Path_Straight_cell172.geometry} material={materials.Stone_Dark} position={[0.1, 0.027, -0.019]} />
      <mesh geometry={nodes.Path_Straight_cell173.geometry} material={materials.Stone_Dark} position={[0.197, 0.004, 0.399]} />
      <mesh geometry={nodes.Path_Straight_cell174.geometry} material={materials.Stone_Dark} position={[0.157, 0.008, 0.432]} />
      <mesh geometry={nodes.Path_Straight_cell175.geometry} material={materials.Stone_Dark} position={[0.103, 0.008, 0.415]} />
      <mesh geometry={nodes.Path_Straight_cell176.geometry} material={materials.Stone_Dark} position={[-0.108, 0.009, 0.419]} />
      <group position={[0.04, 0.035, 0.139]}>
        <mesh geometry={nodes.Path_Straight_cell178_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell178_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell178.geometry} material={materials.Stone_Dark} position={[0.094, 0.027, -0.246]} />
      <mesh geometry={nodes.Path_Straight_cell179.geometry} material={materials.Stone_Dark} position={[0.093, 0.025, -0.298]} />
      <mesh geometry={nodes.Path_Straight_cell180.geometry} material={materials.Stone_Light} position={[-0.149, 0.035, 0.048]} />
      <group position={[-0.15, 0.033, -0.018]}>
        <mesh geometry={nodes.Path_Straight_cell182_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell182_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.209, 0.031, 0.334]}>
        <mesh geometry={nodes.Path_Straight_cell183_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell183_2.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh geometry={nodes.Path_Straight_cell183.geometry} material={materials.Stone_Light} position={[0.167, 0.032, 0.317]} />
      <mesh geometry={nodes.Path_Straight_cell184.geometry} material={materials.Stone_Dark} position={[0.162, 0.023, -0.063]} />
      <mesh geometry={nodes.Path_Straight_cell185.geometry} material={materials.Stone_Dark} position={[0.106, 0.033, -0.082]} />
      <mesh geometry={nodes.Path_Straight_cell186.geometry} material={materials.Stone_Light} position={[0.062, 0.01, 0.173]} />
      <mesh geometry={nodes.Path_Straight_cell187.geometry} material={materials.Stone_Dark} position={[0.003, 0.019, 0.197]} />
      <mesh geometry={nodes.Path_Straight_cell188.geometry} material={materials.Stone_Dark} position={[0.108, 0.008, 0.114]} />
      <mesh geometry={nodes.Path_Straight_cell189.geometry} material={materials.Stone_Dark} position={[0.101, 0.01, 0.121]} />
      <mesh geometry={nodes.Path_Straight_cell190.geometry} material={materials.Stone_Light} position={[0.157, 0.029, 0.388]} />
      <group position={[0.16, 0.029, 0.439]}>
        <mesh geometry={nodes.Path_Straight_cell192_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell192_2.geometry} material={materials.Stone_Dark} />
      </group>
      <group position={[0.208, 0.027, 0.393]}>
        <mesh geometry={nodes.Path_Straight_cell193.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_cell193_1.geometry} material={materials.Stone_Dark} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Path_Straight.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Path_Straight_1.geometry} material={materials.Stone_Dark} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/bricked_wall.glb')
